Feature/financial categories tabs
zero-to-mastery/project_paycheck pull request #17
Opened 2019-07-20 21:11 UTC by nesharim

Will add the redux part a little. As of now build the page so that it has an almost close match to the mock up. Also after approval will get this merged once Nav bar PR has been merged.

![edit](https://user-images.githubusercontent.com/26603483/61584170-eb09aa00-ab60-11e9-9b4d-ebb71633f17a.PNG)

![main](https://user-images.githubusercontent.com/26603483/61584174-fceb4d00-ab60-11e9-9055-4b0541357990.PNG)

![row-deleted](https://user-images.githubusercontent.com/26603483/61584178-02489780-ab61-11e9-8828-dd1fd01686fc.PNG)

2019-07-20 22:11 UTC, ghost requested changes

2019-07-20 22:11 UTC, ghost commented on client/src/App.js
> +      <PaycheckCard/> */}
Typically I would tell you to not include commented-out code in your PRs but seeing how the routes are not done, it's fine

2019-07-20 22:11 UTC, ghost commented on client/public/index.html
> +    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
Please remove. We already have material icons set up as a dependency, check the package.json file
"@material-ui/icons": "^4.2.1"

2019-07-20 22:11 UTC, Dichotomyy commented on client/src/views/financial-categories/forms/category-form.jsx
> +              setTimeout(() => {
The DOCs say to return a promise so I understand why you did this, but this is kinda ugly and hard to read. Please change to use Async/Await. See if this works

```javascript
onRowUpdate: async (newData, oldData) => {
  const data = [...state.data];
  data[data.indexOf(oldData)] = newData;
  setState({ ...state, data });
}
```

2019-07-20 22:11 UTC, Dichotomyy commented on client/src/views/financial-categories/forms/category-form.jsx
> +            }),
could you move these functions out of the return block and make them callback functions that you pass to it? It'll make it easier to read.

2019-07-20 22:11 UTC, Dichotomyy commented on client/src/views/financial-categories/forms/category-form.jsx
> +};
Thank you for using propTypes :D

2019-07-23 17:52 UTC, nesharim commented
@Dichotomyy ready for review

2019-07-23 18:04 UTC, merged